# Values get overwritten by gradle-jenkins
appname: helloworld
image: gluehbirnenkopf/helloworld:1.0
ingress:
domain: some.ingress.host

# Values get taken from here
pullSecret: default-de-icr-io
Ingress:
 enabled: false
 api: extensions/v1beta1
 kind: Ingress

healthCheck:
    path: /actuator/health
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 3
    failureThreshold: 10

deploymentStrategy:
    replicas: 2

configMap:
  values: |-
    message:
      text: I am Gluehbirnenkopf from the cloud
